### ISSUE TITLE
[FEAT] MegaChallenge: 8-bit Fastfetch for FUZIX 8-bit UNIX-Like OS

### ISSUE THREAD

**Issue by Oichkatzelesfrettschen** [fastfetch-cli/fastfetch#1010]
## Wanted features:

After submitting the challenge and request to you to "robustify fastfetch" with Illumos and Solaris, then 16-bit ELKS and 211BSD (and gloworm) the final request for support is fastfetch for the [8-bit FUZIX operating system](https://github.com/EtchedPixels/FUZIX)

## Motivation:

The motivation is to challenge a super-cool dev for one, but you are super busy so I feel bad making that my motivation. My real motivation is to be able to have that sweet, sweet "fastfetch" and logo on (per the dev and creator of FUZIX: *6303, 6502, 65C816, 68000, 6803, 6809, 68HC11, 8080, 8085, arm32, esp8266, MSP430 (bitrotted) and eZ80/Z80/Z180 CPUs* (at least as far as the kernel can boot to userspace is concerned. Otherwise there are more cool things and platforms. 

So that includes modern embedded devices, including Ti-xx graphing calculators (high school and college math class kids showing off their fetch *fetch*? Use case!) as well as for taking pictures to validate a computer or board is indeed running, and a lot more. If [Minecraft-alike-8-bit Blocks](https://www.notin.tokyo/8BB/) can exist, I'm sure that Fastfetch can also exist. :) 

Thank you for your ubermega hard work and wonderful mind. That goes to all the devs I've linked here as well. fastfetch (and the nano text editor) are the missing pieces to feel complete. :)

**Comment by CarterLi** [comment]
Fastfetch is a project that tries to be useful, but the development process was definitely not fun. Fastfetch is highly platform specific. If an API is not available on the platform, you need to find something similar and handle the difference. In worst case you have to [write your own](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/util/windows/getline.c). You have to be aware of the various quirks; you have to test every platform in order to make sure you don't break something when you make any small changes.

That's why we don't support OpenBSD / NetBSD even if we support FreeBSD, although they are all BSDs.

Fastfetch is open-source. I develop fastfetch in my free time. I make absolutely zero income from fastfetch. Instead of "Will you accept my challenge?" you have to accept these challenges yourself.
