### ISSUE TITLE
[BUG] Image logo not working if position is right

### ISSUE THREAD

**Issue by fluffyloopy** [fastfetch-cli/fastfetch#1119]
Be sure to read the [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

# General description of bug:

* What happened:
Image doesn't show up on right. Instead distro ascii logo does. The image does however shows up if i use left or top position.

* What should happen:
image should show up on the right.

* Fastfetch version used: 
```
fastfetch 2.19.1 (x86_64)
```

* Did it work in an older version: 
I have not used any fastfetch versions prior to this.

* Where did you get the binary: 
Github releases

* Does this issue still occur in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)?
Yes

# Often helpful information:

Screenshot:
Using with "position": "left":
![image](https://github.com/user-attachments/assets/e3ab6b86-dd8f-4124-a348-cb587427b264)

Using with "position": "right":
![image](https://github.com/user-attachments/assets/1e04173d-aee5-4a71-986b-7b61cfdbad87)

The content of the configuration file you use (if any):
```
    "logo": {
        "source": "~/.config/fastfetch/logo.png",
        "type": "kitty-direct",
        "position": "right"
    },
```

**Comment by CarterLi** [comment]
In order to print logo at the right side of terminal, fastfetch must move the cursor to right side first. In addition, fastfetch must leave a space for the image, so we need to know the image width

You need to specify the image width and height for now. [After the next version is released](https://github.com/fastfetch-cli/fastfetch/commit/640d0666fcc0e832a9a10f37b293afdb5e4825e9), you  need to specify the image width only.
