### ISSUE TITLE
[FEAT] macOS Sequoia 15.0 cannot obtain Wi-Fi information

### ISSUE THREAD

**Issue by Aoang** [fastfetch-cli/fastfetch#1194]
Be sure to read [FAQ](https://github.com/fastfetch-cli/fastfetch?tab=readme-ov-file#faq) before submitting a new issue.

## Wanted features:

```shell
> fastfetch -s wifi --format json
[
  {
    "type": "Wifi",
    "result": [
      {
        "inf": {
          "description": "en0",
          "status": "Power On"
        },
        "conn": {
          "status": "Active",
          "ssid": "<unknown ssid>",
          "bssid": "",
          "protocol": "Unknown (32)",
          "security": "Insecure",
          "signalQuality": 100.0,
          "rxRate": null,
          "txRate": 866.0
        }
      }
    ]
  }
]
```

- System Version `macOS Sequoia 15.0 Public Beta 6 (24A5320a)`
- Machine `MacBook Pro '14 2021 - Apple M1 Max`

**Comment by CarterLi** [comment]
Let's wait the stable version

**Comment by Princess-Sunset-Shimmer** [comment]
> Let's wait the stable version

When's stable version?
And help:
    1). after new fastfetch update; it print 8 colors instead of 16 colors in `tmux`
    2). Question --> what is ***freq-base*** of CPU that fastfetch fetching? Why my Base-frequency is higher than ***freq-max***? 1.89 GHz ~ 1.80 GHz
![image](https://github.com/user-attachments/assets/43fd45d6-dd79-4b47-aafb-7c5eef7894bf)

**Comment by CarterLi** [comment]
> after new fastfetch update; it print 8 colors instead of 16 colors in `tmux`

Well, yeah. Will fix it in the next version

> Question --> what is freq-base of CPU that fastfetch fetching? Why my Base-frequency is higher than freq-max? 1.89 GHz ~ 1.80 GHz

freq-max is max / turbo / boost frequency (`/sys/devices/system/cpu/cpufreq/policy?/cpuinfo_max_freq`). freq-base is base frequency set by manufacturer (`/sys/devices/system/cpu/cpufreq/policy?/base_frequency`). For Ryzen 7 4800U, the freq-max should be 4.2 GHz, freq-base should be 1.8 GHz.

The problem is that for different platform not all data are available. I don't have AMD CPU, an user told me that AMD doesn't report base frequency (`/sys/devices/system/cpu/cpufreq/policy?/base_frequency`). In VM such as WSL, none of them are available. In this case, real-time current frequency is used as freq-base.

Please check if `/sys/devices/system/cpu/cpufreq/policy?/*` reports correct data. If they doesn't match results reported by fastfetch (`fastfetch -s cpu --format json`), it's a fastfetch bug.

**Comment by Princess-Sunset-Shimmer** [comment]
of course it mismatched;
- - - -
Originally i was trying to dig into `getFrequency` and `detectFrequency` functions for finding out what cause the problem. because i guess probably they cause it. Then i think i'd ask someone more knowledgeable about this before i dig into it by myself -- seems do asking is very correct way to go that now i know what Causes that mismatched base-frequency report.
- - - -
The AMD base-frequency file is `/sys/devices/system/cpu/cpufreq/policy?/cpuinfo_min_freq` NOT is `base_frequency`. Such as Below pic shows base-frequency is 1.4GHz
![image](https://github.com/user-attachments/assets/03e508ef-7c78-41bb-9e35-73d751b7a055)
And mismatched base-frequency is caused by mistakenly report `cpuinfo_cur_freq` file as base-frequency, such here shows 3.44GHz
![image](https://github.com/user-attachments/assets/88e949f7-e178-460b-b380-53810b227c3e)
- - - -

**Comment by CarterLi** [comment]
cpuinfo_min_freq is min frequency, not base frequency. According to <https://www.cpubenchmark.net/cpu.php?id=3721&cpu=AMD+Ryzen+7+4800U>, base freq should be 1.8GHz and max freq should be 4.2GHz

**Comment by CarterLi** [comment]
It's getting off topic. Lets open a new issue.

**Comment by Princess-Sunset-Shimmer** [comment]
> It's getting off topic. Lets open a new issue.

Okay, roger that

**Comment by CarterLi** [comment]
@Princess-Sunset-Shimmer Please try the dev build

**Comment by Princess-Sunset-Shimmer** [comment]
> @Princess-Sunset-Shimmer Please try the dev build
dev build?\
received: and i just now git cloned current newest fastfetch repo
[__> and i'd like to confirm that is `run.sh` pkg-building-script? [Y/n]
![image](https://github.com/user-attachments/assets/7c2f1bbd-9548-4b2f-b113-1777829e2e70)

**Comment by Princess-Sunset-Shimmer** [comment]
Wait, seems i just have a tiny teeny problem while building this pkg at [ 26%]
![image](https://github.com/user-attachments/assets/4f1cf353-761c-4ed5-a099-bfc2ff28c6ca)
What is that?

**Comment by Princess-Sunset-Shimmer** [comment]
Now i goto 😴 💤

**Comment by CarterLi** [comment]
You can download artifacts here: https://github.com/fastfetch-cli/fastfetch/actions/runs/10440218362#artifacts

**Comment by Princess-Sunset-Shimmer** [comment]
i installed:
![image](https://github.com/user-attachments/assets/9d0bde87-9f92-494d-99e8-09f4ac422b14)
And fastfetched the freq-base is **2.50 GHz**, freq-max is **1.80GHz**
![image](https://github.com/user-attachments/assets/5af15eeb-56af-4b57-976e-225a693bb988)
So ... ?

**Comment by CarterLi** [comment]
Please take screenshot of `fastfetch -s cpu --format json`

**Comment by Princess-Sunset-Shimmer** [comment]
> Please take screenshot of `fastfetch -s cpu --format json`

![image](https://github.com/user-attachments/assets/8de974bb-1a52-4524-a8a5-3b431c5e914b)

**Comment by CarterLi** [comment]
Seems your AMD CPU doesn't support CPUID(0x16)

Please try this C program:

```c
#include <cpuid.h>

int main(void)
{
    uint32_t base = 0, max = 0, bus = 0, unused = 0;
    if (!__get_cpuid(0x16, &base, &max, &bus, &unused))
        puts("CPUID(0x16) failed");
    else
        printf("CPUID(0x16) = %u %u %u %u\n", base, max, bus, unused);
    return 0;
}
```

**Comment by Princess-Sunset-Shimmer** [comment]
Okay, wait a sec

**Comment by Princess-Sunset-Shimmer** [comment]
Yeah, the testing result confirms the CPUID(0x16) is not supported:
![image](https://github.com/user-attachments/assets/456f2181-2d91-426c-b53c-fec70976a968)

**Comment by CarterLi** [comment]
I have no other ideas. Let's leave as it was.

**Comment by Princess-Sunset-Shimmer** [comment]
So that very explained why cpu_freq_info cannot be fetched correctly. Mystery declassified

**Comment by Princess-Sunset-Shimmer** [comment]
> I have no other ideas. Let's leave as it was.

Yeah, the PFI-leaf is not supported; sort of as early said, this problem cannot be solved by dig into fastfetch source-code; is not fastfetch caused; is AMD's fault. (but earlier also got very wrong idea what cause it too, now i knows is caused by no PFI-leaf returns need info. Leans a lot)
