### ISSUE TITLE
[BUG] Wrong init and no DE

### ISSUE THREAD

**Issue by realroot2185** [fastfetch-cli/fastfetch#1344]
It's the package from [edge](https://pkgs.alpinelinux.org/package/edge/community/aarch64/fastfetch):
```
fastfetch -v
fastfetch 2.27.1 (aarch64)
```
```
OS: postmarketOS v24.06 aarch64
Init System: busybox
```
I believe that the init is openrc and not busybox am I wrong?

In the config I have DE but it does not show it.
Is that the file that launch the session?
For example `/usr/share/xsessions/bspwm.desktop`.

**Comment by AlbydST** [comment]
This happens for all userlands which have a shell built into them, including `busybox` and `toybox`.

**Comment by CarterLi** [comment]
The `InitSystem` module in fastfetch reports [the first process started by kernel](https://en.wikipedia.org/wiki/Init). In your case, it's busybox. This process is not necessarily the real process that **initializes** your system, because it can delegate the task of initializing the system to another process. See `/etc/inittab`.
