### ISSUE TITLE
WSL Support (again)

### ISSUE THREAD

**Issue by amzon-ex** [fastfetch-cli/fastfetch#483]
In an FR in this repo filed a year ago: https://github.com/fastfetch-cli/fastfetch/issues/174, I requested a way to display more sensible names for GPUs in WSL, as the currently displayed names are generic ones. 

Now that you've added Windows support (which I also use), wouldn't it be possible to display the GPU names "correctly" in WSL? Typically, _if interoperability in WSL is turned on_, one can simply run Windows executables in WSL. For instance, I can run `wmic.exe` to get the names of both the integrated and discrete GPU on my laptop.

**Comment by CarterLi** [comment]
What we displayed ( `Microsoft Corporation Basic Render Driver` for me ) is correct, because that is what the WSL kernel reports.

But yes, it's not very useful. We can get the *currect* information through `wmic.exe` as you suggest. In fact because we can run win32 programs in WSL, we can run a PowerShell script through `pwsh.exe`. And since [PowerShell support Win32 API interaction](https://devblogs.microsoft.com/scripting/use-powershell-to-interact-with-the-windows-api-part-1/), we can call Win32 API directly and get everything as what we can do for a native Win32 program.

We end up with a WSL version fastfetch which generally prints almost the same as the Win32 version fastfetch does. It just runs VERY slow.

My question is: since we can run the Win32 version fastfetch directly in WSL, why not?

**Comment by CarterLi** [comment]
WSL2 is a Linux virtual machine. Let's limit the scope in what Linux can do, as much as we can.

**Comment by amzon-ex** [comment]
Okay. I agree with what you say. I have counterarguments, but I have decided I'll not push the point further. 

Great software, thanks for continuing to develop fastfetch.

**Comment by CarterLi** [comment]
You can do what you want with `command` module (not tested):

```
fastfetch -s command --command-key GPU --command-text "wmic.exe path Win32_VideoController get name | tail -n +2"
```

PS: Good to see some Windows fastfetch users besides me. I have more motivation to develop it.

**Comment by amzon-ex** [comment]
> You can do what you want with `command` module (not tested):
> 
> ```
> fastfetch -s command --command-key GPU --command-text "wmic.exe path Win32_VideoController get name | tail -n +2"
> ```
> 
> PS: Glad to see some Windows fastfetch users besides me. I have more motivation to develop it.

Thanks, @CarterLi  and sorry for being out of the loop. I'll try this out in due time. Also, please keep developing fastfetch for Windows. All the power to you.

**Comment by CarterLi** [comment]
Hello! I find a native way to [fetch the real GPU names in WSL2](https://github.com/fastfetch-cli/fastfetch/commit/8cbe3f6453cbf81178f6c6cdc419dd583d808dec). You may have a try.

If you compile fastfetch yourself, you need [DirectX-Headers](https://github.com/microsoft/DirectX-Headers) installed.

**Comment by amzon-ex** [comment]
Wow, that's amazing, @CarterLi ! Will this be available in release 2.1.0?

**Comment by CarterLi** [comment]
Yes.

**Comment by amzon-ex** [comment]
Thank you. Tried it out and works as expected!
