### ISSUE TITLE
[IMPROVEMENT] FreeBSD installation with pkg

### ISSUE THREAD

**Issue by icaksh** [fastfetch-cli/fastfetch#680]
![Screenshot 2024-01-06 232515](https://github.com/fastfetch-cli/fastfetch/assets/19889081/fca04155-aef3-4186-a1e5-2c85eee1b4a7)

As FreeBSD user, installing 124 packages for fastfetch is absolutely unacceptable except for compiling.

# Current state:
124 packages for fastfetch installation using pkg 

```shell
pkg install fastfetch
```

# Wanted state:
![image](https://github.com/fastfetch-cli/fastfetch/assets/19889081/3b83e536-2444-4b29-a56f-84091f40951d)

- Use minimal packages, like neovim (neovim only install bash)
- Remove dependencies package for fastfetch installation with pkg

# Why the change is sensible:
- For FreeBSD server, I dont need to install wayland or something.

**Comment by CarterLi** [comment]
All deps are optional at runtime because fastfetch loads them dynamically.

@pkubaj Can you please check it?

**Comment by pkubaj** [comment]
Users can install fastfetch-lite, which has all the options disabled.

**Comment by icaksh** [comment]
> Users can install fastfetch-lite, which has all the options disabled.

Okay, thanks for explanation, I will add PR for readme update

**Comment by CarterLi** [comment]
@pkubaj I just checked fastfetch-lite. I found it was built without any dependencies and that was not fastfetch intended to work.

fastfetch should be built with all dependencies installed and enabled, but not necesarily be run with any dependencies installed. Fastfetch uses `dlopen` to load dependencies dynamically at runtime, so that users can install deps they need and the feature will work. However it requires the dependencies being installed when building fastfetch because fastfetch uses it for API / function declarations.

For example, fastfetch uses `sqlite3` for pkg package counting. Because freebsd pre-installs pkg package manager, freebsd users are likely to have `sqlite3` installed. So that the feature works out of box.

I suggest that fastfetch should be built with all dependencies installed and make them build-requirement only. fastfetch-lite should be removed to prevent users from confusing.

**Comment by CarterLi** [comment]
@icaksh You may use the artifacts provided in the release page for now.

**Comment by CarterLi** [comment]
> You're only partially right. `pkg` uses `sqlite3`, but this `sqlite3` isn't supposed to be used by ports, it's for the base system only. Users should install `sqlite3` port on their own and they may not have it installed.

Okey.

@icaksh Please try again after the package gets updated. `Packages` and `Display` module should work. Also you should make your terminal wider, or use a smaller logo (`-l small` should work)

**Comment by icaksh** [comment]
@CarterLi as your wish


![image](https://github.com/fastfetch-cli/fastfetch/assets/19889081/2cf6b511-50b4-47b9-b585-8d7d424b385d)

**Comment by icaksh** [comment]
@pkubaj can you fix for arm64/aarch64 too?

**Comment by pkubaj** [comment]
It's already fixed for all the architectures.
