### ISSUE TITLE
[BUG] Config path not working/detected

### ISSUE THREAD

**Issue by hanzbadua** [fastfetch-cli/fastfetch#901]
# General description of bug:
`fastfetch --list-config-paths` outputs `~/.config/fastfetch/` but config files in this directory are not detected when attempting to run `fastfetch -c configName.jsonc`
* What happened: **config files in aforementioned directory not detected**
* What should happen: **config files should be detected**
* Fastfetch version used: **fastfetch 2.11.5-debug (x86_64)**
* Did it work in an older version: **n/a**
* Where did you get the binary: **pacman**
* Does this issue still occurs in [the latest dev build](https://github.com/fastfetch-cli/fastfetch/actions/)? **Yes, tested commit `c213b07`**

# Often helpful information:

Screenshot:
![Screenshot_20240506_085222](https://github.com/fastfetch-cli/fastfetch/assets/37808762/8e6710f9-7e8b-4ad8-983e-9d38846cd90d)

The content of the configuration file you use (if any):
```
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "modules": [
    "title",
    "separator",
    "os",
    "kernel",
    "uptime",
    "packages",
    "processes",
    "shell",
    "display",
    "lm",
    "de",
    "wm",
    "terminal",
    "cpu",
    "gpu",
    "opengl",
    "vulkan",
    "memory",
    "disk",
    "physicaldisk",
    "locale",
    "break",
    "version",
    "colors"
  ]
}

```

Output of `fastfetch -c ci.jsonc --format json`: **irrelevant**

Output of `fastfetch --list-features`:
```
threads
vulkan
wayland
xcb-randr
xcb
xrandr
x11
drm
gio
dconf
dbus
imagemagick7
chafa
zlib
xfconf
egl
glx
osmesa
opencl
libpulse
libnm
libddcutil
Directx Headers
Proprietary GPU driver API
System yyjson
linux/videodev2
linux/wireless
```

**Comment by CarterLi** [comment]
This is by design. `fastfetch --list-config-paths` is used to searching for config file with default name (i.e. `config.jsonc`). for `-c`, we expect the absolute path is specified. If the file doesn't exist, we assume it being a preset config file name, which is searched in the order of `fastfetch --list-data-paths`

1. `fastfetch -c ~/.config/fastfetch/configName.jsonc`: load user config
3. `fastfetch -c all.jsonc`: load preset (`/usr/share/fastfetch/all.jsonc`, specified in `fastfetch --list-data-paths`)
